Repository DEPthes/3rd-MVP-NoPlanB-Android, pull requests merged in 2024-08, with the labels that each got.

#14 Calendar 페이지 View
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/DayAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/MonthAdapter.kt
  GrowMe/app/src/main/res/drawable/shape_circle.xml
  GrowMe/app/src/main/res/layout/fragment_calendar.xml
  GrowMe/app/src/main/res/layout/item_day.xml
  GrowMe/app/src/main/res/layout/item_month.xml
Labels: FEAT

#15 마이페이지 view 작업, CustomDialog추가
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/DayAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/TodayQuestAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
  GrowMe/app/src/main/res/drawable/dialog_add_quest.png
  GrowMe/app/src/main/res/drawable/dialog_done_quest.png
  GrowMe/app/src/main/res/drawable/dialog_end_today_quest.png
  GrowMe/app/src/main/res/drawable/dialog_levelup.png
  GrowMe/app/src/main/res/drawable/dialog_levelup_unlock.png
  GrowMe/app/src/main/res/drawable/dialog_modify_quest.png
  GrowMe/app/src/main/res/drawable/ic_down.xml
  GrowMe/app/src/main/res/drawable/ic_growme.xml
  GrowMe/app/src/main/res/drawable/ic_up.xml
  GrowMe/app/src/main/res/drawable/img_btn_cancel.png
  GrowMe/app/src/main/res/drawable/img_btn_delete.png
  GrowMe/app/src/main/res/drawable/img_btn_get.png
  GrowMe/app/src/main/res/drawable/img_btn_modify.png
  GrowMe/app/src/main/res/drawable/img_btn_ok.png
  GrowMe/app/src/main/res/drawable/shape_corner_12.xml
  GrowMe/app/src/main/res/drawable/shape_corner_40.xml
  GrowMe/app/src/main/res/drawable/shape_corner_lbrb_12.xml
  GrowMe/app/src/main/res/drawable/shape_corner_ltrt_12.xml
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/dialog_done_all_quest.xml
  GrowMe/app/src/main/res/layout/dialog_done_quest.xml
  GrowMe/app/src/main/res/layout/dialog_levelup.xml
  GrowMe/app/src/main/res/layout/dialog_levelup_unlock.xml
  GrowMe/app/src/main/res/layout/dialog_login_success.xml
  GrowMe/app/src/main/res/layout/dialog_modify_quest.xml
  GrowMe/app/src/main/res/layout/fragment_calendar.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_item.xml
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
  GrowMe/app/src/main/res/layout/fragment_setting.xml
  GrowMe/app/src/main/res/values/colors.xml
Labels: FEAT, setting

#21 [Fix] Item View 작업
  GrowMe/app/src/main/java/com/growme/growme/data/model/MonthExp.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/Quest.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/TodayQuest.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/DayAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/MonthAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/QuestRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/TodayQuestAdapter.kt
  GrowMe/app/src/main/res/drawable/shape_rectangle_black_calendar.xml
  GrowMe/app/src/main/res/drawable/shape_rectangle_gray.xml
  GrowMe/app/src/main/res/drawable/shape_rectangle_gray_calendar.xml
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/dialog_modify_quest.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/item_day.xml
  GrowMe/app/src/main/res/layout/item_quest.xml
Labels: FEAT, FIX, setting

#22 Fix/character setting
  GrowMe/app/build.gradle.kts
  GrowMe/app/src/main/AndroidManifest.xml
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/CharacterSettingActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/res/drawable/btn_start.png
  GrowMe/app/src/main/res/drawable/character_1.png
  GrowMe/app/src/main/res/drawable/character_2.png
  GrowMe/app/src/main/res/drawable/character_3.png
  GrowMe/app/src/main/res/drawable/clothes_1.png
  GrowMe/app/src/main/res/drawable/clothes_2.png
  GrowMe/app/src/main/res/drawable/clothes_mini_1.png
  GrowMe/app/src/main/res/drawable/clothes_mini_2.png
  GrowMe/app/src/main/res/drawable/dialog.png
  GrowMe/app/src/main/res/drawable/face_1.png
  GrowMe/app/src/main/res/drawable/face_2.png
  GrowMe/app/src/main/res/drawable/face_3.png
  GrowMe/app/src/main/res/drawable/face_mini_1.png
  GrowMe/app/src/main/res/drawable/face_mini_2.png
  GrowMe/app/src/main/res/drawable/face_mini_3.png
  GrowMe/app/src/main/res/drawable/hair1_for_total_character.png
  GrowMe/app/src/main/res/drawable/hair2_for_total_character.png
  GrowMe/app/src/main/res/drawable/hair3_for_total_character.png
  GrowMe/app/src/main/res/drawable/hair_big1.png
  GrowMe/app/src/main/res/drawable/hair_big2.png
  GrowMe/app/src/main/res/drawable/hair_big3.png
  GrowMe/app/src/main/res/drawable/head_1.png
  GrowMe/app/src/main/res/drawable/head_2.png
  GrowMe/app/src/main/res/drawable/head_3.png
  GrowMe/app/src/main/res/drawable/ic_edit_name.xml
  GrowMe/app/src/main/res/drawable/img_character_screen.png
  GrowMe/app/src/main/res/drawable/page_title.png
  GrowMe/app/src/main/res/drawable/skin_1.png
  GrowMe/app/src/main/res/drawable/skin_2.png
  GrowMe/app/src/main/res/drawable/skin_3.png
  GrowMe/app/src/main/res/drawable/skin_big1.png
  GrowMe/app/src/main/res/drawable/skin_mini_1.png
  GrowMe/app/src/main/res/drawable/skin_mini_2.png
  GrowMe/app/src/main/res/drawable/skin_mini_3.png
  GrowMe/app/src/main/res/layout/activity_character_setting.xml
  GrowMe/app/src/main/res/layout/fragment_clothes_setting.xml
  GrowMe/app/src/main/res/layout/fragment_face_setting.xml
  GrowMe/app/src/main/res/layout/fragment_hair_setting.xml
  GrowMe/app/src/main/res/layout/fragment_name_setting.xml
  GrowMe/app/src/main/res/layout/fragment_setting_complete.xml
  GrowMe/app/src/main/res/layout/fragment_skin_setting.xml
  GrowMe/gradle/libs.versions.toml
Labels: FIX, setting

#24 [Fix] CleanUp project
  GrowMe/app/src/main/java/com/growme/growme/data/remote/KakaoAuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/CharacterSettingActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/res/drawable/ic_edit_name.xml
  GrowMe/app/src/main/res/drawable/shape_corner_8.xml
  GrowMe/app/src/main/res/layout/fragment_clothes_setting.xml
  GrowMe/app/src/main/res/layout/fragment_face_setting.xml
  GrowMe/app/src/main/res/layout/fragment_hair_setting.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_name_setting.xml
  GrowMe/app/src/main/res/layout/fragment_setting_complete.xml
  GrowMe/app/src/main/res/layout/fragment_skin_setting.xml
  GrowMe/app/src/main/res/values/strings.xml
Labels: CHORE

#26 [Fix] Item page
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/res/drawable/bottom_navi_selected.xml
  GrowMe/app/src/main/res/drawable/ic_item_navi_background.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_face.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_fashion.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_hair.png
  GrowMe/app/src/main/res/drawable/img_effect_light.png
  GrowMe/app/src/main/res/drawable/tab_item_selected.xml
  GrowMe/app/src/main/res/drawable/tab_item_unselected.xml
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/fragment_clothes_setting.xml
  GrowMe/app/src/main/res/layout/fragment_face_setting.xml
  GrowMe/app/src/main/res/layout/fragment_hair_setting.xml
  GrowMe/app/src/main/res/layout/fragment_item.xml
  GrowMe/app/src/main/res/layout/fragment_name_setting.xml
  GrowMe/app/src/main/res/layout/fragment_setting_complete.xml
  GrowMe/app/src/main/res/layout/fragment_skin_setting.xml
  GrowMe/app/src/main/res/raw/animation.gif
  GrowMe/app/src/main/res/values/strings.xml
Labels: FIX

#27 [Feat] API 세팅
  GrowMe/app/build.gradle.kts
  GrowMe/app/src/main/AndroidManifest.xml
  GrowMe/app/src/main/java/com/growme/growme/data/LoggerUtils.kt
  GrowMe/app/src/main/java/com/growme/growme/data/RetrofitClient.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/auth/GetAccessTokenRequestDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/auth/GetAccessTokenResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/auth/Information.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/calendar/GetCalendarResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/ChangeNicknameRequestDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/ChangeNicknameResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/CharacterInfoResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/GetCharacterItemResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/MyCharaterDetailRes.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/AddQuestRequestDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/CUDQuestResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/MainResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/QuestResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/UpdateQuestRequestDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/remote/KakaoAuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/AuthRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserPreferencesRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/AuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/CalendarService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/CharacterService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/KakaoAuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/QuestService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/CUDQuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/HomeInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/LoginResponseEntity.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/QuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/AuthRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/QuestRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/UserPreferencesRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/base/GlobalApplication.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/UserRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/splash/SplashActivity.kt
Labels: FEAT, CHORE, setting

#29 [Feat] Home 화면 퀘스트 작업
  GrowMe/app/src/main/java/com/growme/growme/data/repository/AuthRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/KakaoAuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/QuestService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/QuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/character/MyPageInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/quest/AddQuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/quest/QuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/QuestRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/CharacterSettingActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/QuestRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/splash/SplashActivity.kt
  GrowMe/app/src/main/res/layout/activity_character_setting.xml
Labels: FEAT, CHORE

#31 MyPage 화면 API 작업
  GrowMe/app/src/main/java/com/growme/growme/data/model/user/UserEmailResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CharacterRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/UserService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/UserRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/UserRepository.kt
  GrowMe/app/src/main/res/drawable/ic_setting.png
  GrowMe/app/src/main/res/drawable/img_logo_mypage.png
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
  GrowMe/app/src/main/res/layout/fragment_setting.xml
  GrowMe/app/src/main/res/values/colors.xml
Labels: FEAT, CHORE

#33 [Fix] Service 수정, CleanUp
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/GetInitialResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CharacterRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/CalendarService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/CharacterService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/QuestService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/UserService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/character/CharacterInitialInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/character/GetCharacterItemInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/CharacterRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
Labels: CHORE

#34 [Fix] ToolBar 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
  GrowMe/app/src/main/res/drawable/img_logo_mypage.png
  GrowMe/app/src/main/res/drawable/img_logo_right.png
  GrowMe/app/src/main/res/drawable/img_logo_title.png
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/activity_signin.xml
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/dialog_done_all_quest.xml
  GrowMe/app/src/main/res/layout/dialog_done_quest.xml
  GrowMe/app/src/main/res/layout/dialog_levelup.xml
  GrowMe/app/src/main/res/layout/dialog_levelup_unlock.xml
  GrowMe/app/src/main/res/layout/dialog_login_success.xml
  GrowMe/app/src/main/res/layout/dialog_modify_quest.xml
  GrowMe/app/src/main/res/layout/fragment_calendar.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
  GrowMe/app/src/main/res/layout/fragment_setting.xml
  GrowMe/app/src/main/res/layout/item_day.xml
  GrowMe/app/src/main/res/layout/item_month.xml
  GrowMe/app/src/main/res/layout/item_quest.xml
  GrowMe/app/src/main/res/values/strings.xml
Labels: FIX, CHORE

#37 [Feat] Home 화면 퀘스트 추가, 수정, 삭제
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/home/HomeExpInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/QuestRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
  GrowMe/app/src/main/res/layout/fragment_home.xml
Labels: FEAT

#41 [Feat] Mypage, Home 화면 캐릭터 정보 연동
  GrowMe/app/src/main/java/com/growme/growme/domain/model/home/ItemData.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
Labels: FEAT, FIX

#43 Feat/item api
  GrowMe/app/src/main/java/com/growme/growme/data/model/Item.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/CategoryItem.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/ItemChangeDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/ItemDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/MyCharacterEquipItemDetailReq.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/ItemRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/ItemChangeService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/ItemService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/ItemInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/ItemRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemViewModel.kt
  GrowMe/app/src/main/res/drawable/ic_item_navi_background.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_face.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_fashion.png
  GrowMe/app/src/main/res/drawable/ic_item_navi_hair.png
  GrowMe/app/src/main/res/drawable/ic_locked.xml
  GrowMe/app/src/main/res/drawable/iv_item_locked.png
  GrowMe/app/src/main/res/layout/fragment_item.xml
  GrowMe/app/src/main/res/layout/item_inventory.xml
Labels: FEAT

#44 [Feat] Calendar 화면 오늘 이후 날짜 퀘스트 작업
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/QuestRvAdapter.kt
  GrowMe/app/src/main/res/values/colors.xml
Labels: FEAT, CHORE

#45 [Feat] 퀘스트 완료 이후 레벨업, 해금 작업
  GrowMe/app/src/main/java/com/growme/growme/presentation/base/GlobalApplication.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/res/drawable/ic_unlock_more.png
  GrowMe/app/src/main/res/layout/dialog_levelup.xml
  GrowMe/app/src/main/res/layout/dialog_levelup_unlock.xml
Labels: FEAT

#46 Feat/item save api
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/ItemChangeResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/MyCharacterEquipItemDetailReq.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/ItemChangeDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/item/MyCharacterEquipItemDetailReq.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/ItemChangeRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/ItemChangeService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/ItemChangeRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/character/CharacterViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemRvAdapter.kt
  GrowMe/app/src/main/res/layout/fragment_item.xml
Labels: FEAT, FIX

#48 [Refactoring] 디자인 변경에 따른 수정
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CalendarRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/QuestService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/calendar/GetMonthExpInfoItem.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/CalendarRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/CompleteQuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/QuestRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/DayAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/MonthAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/QuestRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/res/drawable/dialog_add_quest.png
  GrowMe/app/src/main/res/drawable/shape_black_circle.xml
  GrowMe/app/src/main/res/drawable/shape_gray_circle.xml
  GrowMe/app/src/main/res/drawable/shape_white_circle.xml
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/fragment_calendar.xml
  GrowMe/app/src/main/res/layout/item_day.xml
Labels: FIX, CHORE

#49 [Fix] QA 1차 수정
  GrowMe/app/src/main/java/com/growme/growme/data/model/quest/MainResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/home/HomeExpInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/CompleteQuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/DayAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/QuestRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
  GrowMe/app/src/main/res/drawable/btn_mini_selected.xml
  GrowMe/app/src/main/res/drawable/shape_yellow_circle.xml
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/dialog_done_all_quest.xml
  GrowMe/app/src/main/res/layout/dialog_modify_quest.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
  GrowMe/app/src/main/res/layout/item_day.xml
Labels: FEAT, FIX

#53 Feat/login api
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/MakeInitCharacterDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/character/MyCharaterDetailRes.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/user/IsUserRegisteredResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CharacterRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/CharacterService.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/UserService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/IsUserRegisteredInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/character/MyCharacterDetailInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/CharacterRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/UserRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/CharacterSettingViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInViewModel.kt
Labels: FEAT

#54 QA 캐릭터 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/res/drawable/bubble_chat1.png
  GrowMe/app/src/main/res/drawable/bubble_chat2.png
  GrowMe/app/src/main/res/drawable/bubble_chat3.png
  GrowMe/app/src/main/res/drawable/bubble_chat4.png
  GrowMe/app/src/main/res/drawable/img_level30_dialog.png
  GrowMe/app/src/main/res/drawable/img_level_up.png
  GrowMe/app/src/main/res/layout/dialog_level_max.xml
  GrowMe/app/src/main/res/layout/dialog_levelup_unlock.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/raw/gif_done_all_quest.gif
  GrowMe/app/src/main/res/raw/gif_done_quest.gif
Labels: FEAT

#55 [Fix] QA 아이템 페이지 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemRvAdapter.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/res/drawable/btn_save.png
  GrowMe/app/src/main/res/drawable/button_save.png
  GrowMe/app/src/main/res/drawable/button_save_locked.png
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/fragment_item.xml
  GrowMe/app/src/main/res/layout/fragment_mypage.xml
  GrowMe/app/src/main/res/layout/item_inventory.xml
Labels: FEAT

#57 캐릭터 말풍선 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
Labels: FIX

#58 퀘스트 다이얼로그, 말풍선 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/res/layout/dialog_add_quest.xml
  GrowMe/app/src/main/res/layout/dialog_modify_quest.xml
  GrowMe/app/src/main/res/layout/fragment_home.xml
  GrowMe/app/src/main/res/layout/item_inventory.xml
  GrowMe/app/src/main/res/values/strings.xml
Labels: FIX, CHORE

#60 회원 탈퇴 기능
  GrowMe/app/src/main/java/com/growme/growme/data/model/Information.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/Item.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/MonthExp.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/MyInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/Quest.kt
  GrowMe/app/src/main/java/com/growme/growme/data/model/user/WithdrawResponseDTO.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CalendarRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/CharacterRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/DataStoreRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/ItemChangeRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/ItemRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/UserService.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/model/quest/CompleteQuestInfo.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/DataStoreRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/QuestRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/domain/repository/UserRepository.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/base/GlobalApplication.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/SettingFragment.kt
Labels: FEAT, FIX, CHORE

#61 초기 캐릭터 설정 수정
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
Labels: FIX, CHORE

#63 QA 최종 테스트 수정
  GrowMe/app/src/main/java/com/growme/growme/data/repository/ItemRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/QuestRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/repository/UserRepositoryImpl.kt
  GrowMe/app/src/main/java/com/growme/growme/data/service/UserService.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/base/GlobalApplication.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SettingCompleteFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInViewModel.kt
  GrowMe/app/src/main/res/color/bottom_navigation_text_color.xml
  GrowMe/app/src/main/res/layout/dialog_done_all_quest.xml
  GrowMe/app/src/main/res/layout/fragment_setting_complete.xml
  GrowMe/app/src/main/res/values/themes.xml
Labels: FEAT, CHORE
