Repository DEPthes/3rd-MVP-NoPlanB-Android, pull requests merged in 2024-07, with the labels that each got.

#2 디자인 시스템
  GrowMe/app/src/main/res/drawable/ic_add_box.xml
  GrowMe/app/src/main/res/drawable/ic_alert.xml
  GrowMe/app/src/main/res/drawable/ic_calendar.xml
  GrowMe/app/src/main/res/drawable/ic_calendar_left.xml
  GrowMe/app/src/main/res/drawable/ic_calendat_right.xml
  GrowMe/app/src/main/res/drawable/ic_camera.xml
  GrowMe/app/src/main/res/drawable/ic_cart.xml
  GrowMe/app/src/main/res/drawable/ic_check.xml
  GrowMe/app/src/main/res/drawable/ic_checkbox.xml
  GrowMe/app/src/main/res/drawable/ic_checkbox_check.xml
  GrowMe/app/src/main/res/drawable/ic_circle.xml
  GrowMe/app/src/main/res/drawable/ic_close.xml
  GrowMe/app/src/main/res/drawable/ic_delete.xml
  GrowMe/app/src/main/res/drawable/ic_edit.xml
  GrowMe/app/src/main/res/drawable/ic_edit_box.xml
  GrowMe/app/src/main/res/drawable/ic_gift.xml
  GrowMe/app/src/main/res/drawable/ic_heart.xml
  GrowMe/app/src/main/res/drawable/ic_heart_full.xml
  GrowMe/app/src/main/res/drawable/ic_home.xml
  GrowMe/app/src/main/res/drawable/ic_left.xml
  GrowMe/app/src/main/res/drawable/ic_loader.xml
  GrowMe/app/src/main/res/drawable/ic_more.xml
  GrowMe/app/src/main/res/drawable/ic_play.xml
  GrowMe/app/src/main/res/drawable/ic_potion.xml
  GrowMe/app/src/main/res/drawable/ic_potion_blue.xml
  GrowMe/app/src/main/res/drawable/ic_potion_green.xml
  GrowMe/app/src/main/res/drawable/ic_potion_orange.xml
  GrowMe/app/src/main/res/drawable/ic_potion_pink.xml
  GrowMe/app/src/main/res/drawable/ic_potion_red.xml
  GrowMe/app/src/main/res/drawable/ic_radio_check.xml
  GrowMe/app/src/main/res/drawable/ic_right.xml
  GrowMe/app/src/main/res/drawable/ic_script.xml
  GrowMe/app/src/main/res/drawable/ic_script_text.xml
  GrowMe/app/src/main/res/drawable/ic_slide.xml
  GrowMe/app/src/main/res/drawable/ic_smile.xml
  GrowMe/app/src/main/res/drawable/ic_trash.xml
  GrowMe/app/src/main/res/drawable/ic_user.xml
  GrowMe/app/src/main/res/font/neodgm.ttf
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/menu/bottom_navigation_menu.xml
  GrowMe/app/src/main/res/values/colors.xml
  GrowMe/app/src/main/res/values/font_style.xml
  GrowMe/app/src/main/res/values/strings.xml
  GrowMe/app/src/main/res/values/themes.xml
Labels: setting

#3 [Setting] sdk 버전 변경
  GrowMe/app/build.gradle.kts
Labels: setting

#5 카카오 로그인 연동
  .DS_Store
  GrowMe/app/build.gradle.kts
  GrowMe/app/src/main/AndroidManifest.xml
  GrowMe/app/src/main/java/com/growme/growme/data/RetrofitClient.kt
  GrowMe/app/src/main/java/com/growme/growme/data/remote/KakaoAuthService.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/base/GlobalApplication.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInViewModel.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/splash/SplashActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/splash/SplashViewModel.kt
  GrowMe/app/src/main/res/drawable/btn_kakao_login.png
  GrowMe/app/src/main/res/drawable/login_wallpaper.png
  GrowMe/app/src/main/res/drawable/logo.png
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/activity_signin.xml
  GrowMe/app/src/main/res/layout/activity_splash.xml
  GrowMe/app/src/main/res/values/colors.xml
  GrowMe/app/src/main/res/values/font_style.xml
  GrowMe/app/src/main/res/values/strings.xml
  GrowMe/app/src/main/res/values/themes.xml
  GrowMe/gradle/libs.versions.toml
  GrowMe/settings.gradle.kts
Labels: FEAT, setting

#6 [feat] 캐릭터 설정 화면
  GrowMe/app/src/main/AndroidManifest.xml
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/res/drawable/btn_mini_default.xml
  GrowMe/app/src/main/res/drawable/btn_mini_selected.xml
  GrowMe/app/src/main/res/drawable/btn_next.png
  GrowMe/app/src/main/res/drawable/btn_submit.png
  GrowMe/app/src/main/res/drawable/clothes_1.png
  GrowMe/app/src/main/res/drawable/clothes_2.png
  GrowMe/app/src/main/res/drawable/face_1.png
  GrowMe/app/src/main/res/drawable/face_2.png
  GrowMe/app/src/main/res/drawable/face_3.png
  GrowMe/app/src/main/res/drawable/hair_mini1.png
  GrowMe/app/src/main/res/drawable/hair_mini2.png
  GrowMe/app/src/main/res/drawable/hair_mini3.png
  GrowMe/app/src/main/res/drawable/ic_left_white.xml
  GrowMe/app/src/main/res/drawable/img_ch1_skin.png
  GrowMe/app/src/main/res/drawable/img_ch2_face.png
  GrowMe/app/src/main/res/drawable/img_ch3_hair.png
  GrowMe/app/src/main/res/drawable/img_ch4_cloth.png
  GrowMe/app/src/main/res/drawable/img_ch5_name.png
  GrowMe/app/src/main/res/drawable/img_character_screen.png
  GrowMe/app/src/main/res/drawable/img_level1.png
  GrowMe/app/src/main/res/drawable/img_level2.png
  GrowMe/app/src/main/res/drawable/img_level3.png
  GrowMe/app/src/main/res/drawable/img_level4.png
  GrowMe/app/src/main/res/drawable/img_level5.png
  GrowMe/app/src/main/res/drawable/img_write_name.png
  GrowMe/app/src/main/res/drawable/skin_1.png
  GrowMe/app/src/main/res/drawable/skin_2.png
  GrowMe/app/src/main/res/drawable/skin_3.png
  GrowMe/app/src/main/res/drawable/skin_big1.png
  GrowMe/app/src/main/res/layout/fragment_clothes_setting.xml
  GrowMe/app/src/main/res/layout/fragment_face_setting.xml
  GrowMe/app/src/main/res/layout/fragment_hair_setting.xml
  GrowMe/app/src/main/res/layout/fragment_name_setting.xml
  GrowMe/app/src/main/res/layout/fragment_skin_setting.xml
  GrowMe/app/src/main/res/values/strings.xml
Labels: FEAT

#7 아이템 페이지 view
  GrowMe/app/build.gradle.kts
  GrowMe/app/src/main/AndroidManifest.xml
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/MainActivity.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/calendar/CalendarFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/ClothesSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/FaceSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/HairSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/NameSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/characterSetting/SkinSettingFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/home/HomeFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/item/ItemFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/mypage/MyPageFragment.kt
  GrowMe/app/src/main/java/com/growme/growme/presentation/views/signIn/SignInActivity.kt
  GrowMe/app/src/main/res/drawable/background_1.png
  GrowMe/app/src/main/res/drawable/btn_delete.png
  GrowMe/app/src/main/res/drawable/btn_save.png
  GrowMe/app/src/main/res/drawable/img_character_2.png
  GrowMe/app/src/main/res/drawable/img_character_screen.png
  GrowMe/app/src/main/res/drawable/img_login_done.png
  GrowMe/app/src/main/res/drawable/img_logo_title.png
  GrowMe/app/src/main/res/drawable/img_wallpaper.png
  GrowMe/app/src/main/res/drawable/item_cloth_1.png
  GrowMe/app/src/main/res/drawable/item_cloth_2.png
  GrowMe/app/src/main/res/drawable/item_face_1.png
  GrowMe/app/src/main/res/drawable/item_face_2.png
  GrowMe/app/src/main/res/drawable/item_face_3.png
  GrowMe/app/src/main/res/drawable/item_hair_1.png
  GrowMe/app/src/main/res/drawable/item_hair_2.png
  GrowMe/app/src/main/res/drawable/item_hair_3.png
  GrowMe/app/src/main/res/drawable/login_wallpaper.png
  GrowMe/app/src/main/res/drawable/screen_new.xml
  GrowMe/app/src/main/res/drawable/shape_corner_8.xml
  GrowMe/app/src/main/res/drawable/shape_corner_black.xml
  GrowMe/app/src/main/res/drawable/tab_item_selected.xml
  GrowMe/app/src/main/res/drawable/tab_item_unselected.xml
  GrowMe/app/src/main/res/layout/activity_main.xml
  GrowMe/app/src/main/res/layout/activity_signin.xml
  GrowMe/app/src/main/res/layout/activity_splash.xml
  GrowMe/app/src/main/res/layout/dialog_login_success.xml
  GrowMe/app/src/main/res/layout/fragment_hair_setting.xml
  GrowMe/app/src/main/res/layout/fragment_item.xml
  GrowMe/app/src/main/res/menu/bottom_navigation_menu.xml
  GrowMe/app/src/main/res/values/colors.xml
  GrowMe/app/src/main/res/values/strings.xml
  GrowMe/app/src/main/res/values/themes.xml
Labels: FEAT, CHORE, setting
